title: Jeongbin Bang, 방정빈
author: Jeongbin Bang
url: https://bangjeongbin.github.io # 사이트의 루트 주소
description: > # 사이트 설명 (여러 줄 가능)
  <br>
   -	항상 더 나은 보안 방안을 고민하고 끊임없이 배우는 방정빈입니다. 보안 전문가를 지향하며 논리적 분석을 바탕으로 위협의 본질을 파악하는 전문가가 되기 위해 노력합니다. 또한 새로운 공격 기법에 대한 <strong>도전을 즐기고 책임감 있는 태도</strong>로 보안 사고에 대응하며 <strong>같이 일하고 싶은 사람</strong>을 목표로 하고 있습니다. <br> <br>
   -	매일매일 네트워크, 운영체제, 취약점 분석, 해킹 등 보안관련 학습과 관심있는 보안 서적으로 공부하는 등 모든 면에서 지금보다 발전하고자 하는 <strong>향상심을 가지며 배움에 많은 시간을 투자</strong>하는 편입니다. <br> <br>
   -	개발 경험을 바탕으로 Java, Spring, RESTful API를 이해하고 있으며, AWS와 Linux, Git을 활용한 인프라 환경에 익숙합니다. 현재는 네트워크 프로토콜, 보안 시스템, 최신 위협 동향을 학습하며 정보보안전문가로 성장하기 위해 준비하고 있습니다. <br> <br>


permalink: /:slug # 페이지의 기본 URL 형식

favicon: "./logo.png" # 사이트 파비콘의 상대 경로

twitter:
    username: abhinav # 트위터 사용자명 (필요에 따라 수정 또는 삭제 가능)
    card: summary_large_image # 트위터 카드 스타일

#theme: moonwalk # GitHub Pages를 사용하는 경우, 아래 설정을 사용해야 함
remote_theme: abhinavs/moonwalk # 원격 테마 설정

theme_config:
  appearance: "auto" # 테마 모드 설정 ("light", "dark", "auto" 중 선택)
  appearance_toggle: true # 사용자가 테마 모드를 변경할 수 있도록 허용
  back_home_text: "home.." # 게시물 레이아웃에서 홈 링크의 텍스트 커스텀 설정
  date_format: "%Y-%m-%d" # 날짜 형식 설정
  show_description: true # 블로그 설명 표시 여부
  show_navbar: true # 가로 네비게이션 바 표시 여부
  show_footer: true # 홈페이지 푸터 링크 표시 여부 (`_data/home.yml`에서 설정 추가 필요)
  show_copyright: true # 푸터에 저작권 표시 여부
  # 아래 설정값은 홈페이지 레이아웃 구성에 사용됨
  show_projects: true # 프로젝트를 카드 형태로 표시 (`_data/home.yml`에서 설정 추가 필요)
  show_blog: true # `_posts` 폴더에 추가된 블로그 게시물 표시 여부
  show_old_projects: true # 이전 프로젝트를 카드 형태로 표시 (`_data/home.yml`에서 설정 추가 필요)
  show_misc_list: true # 기타 정보를 세로 목록 형태로 표시 (`_data/home.yml`에서 설정 추가 필요)
  show_reading_time: true # 블로그 게시물에 단어 수 및 예상 읽기 시간 표시
  show_tags: true # 블로그 게시물에 태그 표시 여부
  # "홈" 페이지의 옵션
  home:
    title_projects: Portfolio # 포트폴리오 섹션 제목
    title_misc_list: Details # 기타 정보 섹션 제목
    title_blog: Blog # 블로그 섹션 제목
    title_old_projects: Old Projects # 이전 프로젝트 섹션 제목

soopr:
  publish_token: "" # https://www.soopr.co 가입 후 공유 및 반응 기능을 개인화하기 위한 토큰 입력

highlighter: rouge # 코드 하이라이터 설정

sass:
  style: :compressed # SASS 스타일 압축 설정

plugins:
  - jekyll-feed # Jekyll RSS 피드 플러그인
  - jekyll-soopr-seo-tag # SEO 최적화를 위한 Soopr 플러그인
